import { useEffect, useState, type ReactNode } from 'react';
import { api } from '../lib/api';
import type { WhatsAppStatus } from '../types';

const LABEL:Record<WhatsAppStatus['state'],string>={CONNECTED:'Conectado',CONNECTING:'Conectando',QR_REQUIRED:'QR Code necessário',DISCONNECTED:'Desconectado',ERROR:'Erro'};

export function WhatsAppPage():ReactNode {
  const [status,setStatus]=useState<WhatsAppStatus|null>(null),[qr,setQr]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function refresh(){try{const result=await api.getWhatsAppQr();setStatus(result.status);setQr(result.qr);setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao consultar WhatsApp.');}}
  useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),3000);return()=>window.clearInterval(timer);},[]);
  async function connect(){setBusy(true);try{setStatus(await api.connectWhatsApp());await refresh();}catch(e){setError(e instanceof Error?e.message:'Falha ao conectar.');}finally{setBusy(false);}}
  async function disconnect(){if(!window.confirm('Desconectar este WhatsApp? O logout do dashboard não faz isso.'))return;setBusy(true);try{setStatus(await api.disconnectWhatsApp());setQr(null);}catch(e){setError(e instanceof Error?e.message:'Falha ao desconectar.');}finally{setBusy(false);}}
  return <div className="space-y-6"><div><p className="text-sm text-cyan-400">Canal da empresa</p><h2 className="mt-1 text-2xl font-semibold">WhatsApp</h2><p className="mt-2 text-sm text-slate-400">A conexão exibida aqui pertence exclusivamente à sua empresa.</p></div>{error&&<div role="alert" className="rounded-xl bg-red-500/10 p-4 text-red-300">{error}</div>}<section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="font-semibold">Status da sessão</h3><div className="mt-5 flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${status?.state==='CONNECTED'?'bg-emerald-400':status?.state==='ERROR'?'bg-red-400':'bg-amber-400'}`}/><strong className="text-lg">{status?LABEL[status.state]:'Carregando…'}</strong></div>{status?.lastError&&<p className="mt-3 text-sm text-red-300">{status.lastError}</p>}<div className="mt-6 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void connect()} className="rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-50">Conectar / reconectar</button><button disabled={busy||!status?.enabled} onClick={()=>void disconnect()} className="rounded-xl border border-slate-700 px-4 py-2.5 text-sm text-slate-200 disabled:opacity-50">Desconectar WhatsApp</button></div><p className="mt-4 text-xs text-slate-500">Sair do dashboard não desconecta o WhatsApp.</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="font-semibold">QR Code</h3>{qr?<div className="mt-4 rounded-2xl bg-white p-4"><img src={qr} alt="QR Code para conectar o WhatsApp" className="mx-auto aspect-square w-full max-w-xs"/></div>:<div className="mt-4 grid min-h-64 place-items-center rounded-xl border border-dashed border-slate-700 text-center text-sm text-slate-500">{status?.state==='CONNECTED'?'Sessão já autenticada. Nenhum QR necessário.':'O QR aparecerá aqui quando o WhatsApp solicitar autenticação.'}</div>}</div></section></div>;
}
